### ISSUE TITLE
aria-label property

### ISSUE THREAD

**Issue by kulbabskyy** [tigrr/circle-progress#38]
Helo Tigran,

I have another small improvement related to the screen readers. 
The SVG now has all the required aria attributes excluding the aria-label attribute.

Can it be possible to have an aria-label property we can set from the <circle-progress> tag or via jsvascript attributes?
Also it is nice idea to make a fallback if the aria-label is empty like: "value of max".

Best Regards,
Anatoliy

**Comment by tigrr** [comment]
You can set `aria-label` on `circle-progress` as on any other HTML element. Circle Progress is no special in that regard.
The role and value / max attributes already provide assistive technologies with all the necessary info, which they announce to their user. No need to additionally pass text, such as "value of max", especially since that text is in only one language - English.

**Comment by kulbabskyy** [comment]
Thank you for the reply. 

This is the approach I currently using, but if the <svg> inside <circle-progress> has additional ARIA attributes (like aria-valuenow, aria-valuemax, etc.), they may be ignored or redundantly announced because the screen reader prefers the aria-label on the parent <circle-progress>

**Comment by tigrr** [comment]
It is not the attributes that are redundant, it is `aria-label`. You don't need to set it. All the progress information is already conveyed to the user by assistive technology in the most native amd convenient way in user's language.

**Comment by kulbabskyy** [comment]
ok, lest close this issue, thank you!
